from app.llm import invoke_llm
from app.utils.prompt_templates import refrence_sort_template, index_sort_template
from app.utils.llm_response_parser import extract_json_from_llm_response
import json, os
import ast

output_directory = "sorted_references"
os.makedirs(output_directory, exist_ok=True)

def inplace_sort(worklet,model, index):
    """
    Sorts the "Reference Work" section of a given worklet in place using a language model.
    Args:
        worklet (dict): A dictionary containing a "Reference Work" key, which holds the data to be sorted.
        model (str): The name or identifier of the language model to be used for sorting.
        index (int): An index parameter (not used in the current implementation).
    Returns:
        dict: The updated worklet with the "Reference Work" section sorted.
    Raises:
        KeyError: If the "Reference Work" key is not present in the worklet dictionary.
        ValueError: If the response from the language model cannot be parsed into JSON.
    """

    reference_work_str = json.dumps(worklet['Reference Work'], indent=2)
    prompt =refrence_sort_template(reference_work_str)  
    sorted_references = invoke_llm(prompt, model)
    worklet["Reference Work"] = extract_json_from_llm_response(sorted_references)
    return worklet

def scholar_sort(worklet,model,index):
    """
    Sorts the "Reference Work" list within the given worklet dictionary based on the priority of tags.
    The function assigns a priority to each tag ('scholar', 'google', 'github') and sorts the list
    in ascending order of priority. If a tag is not found in the priority dictionary, it defaults
    to the lowest priority.
    Args:
        worklet (dict): A dictionary containing a "Reference Work" key, which maps to a list of
                        dictionaries. Each dictionary in the list must have a 'Tag' key.
        model: Unused parameter in the current implementation.
        index: Unused parameter in the current implementation.
    Returns:
        dict: The modified worklet dictionary with the "Reference Work" list sorted by tag priority.
    """

    priority = {
    'scholar': 0,
    'google': 1,
    'github': 2
    }
    worklet["Reference Work"].sort(key=lambda x: priority.get(x['Tag'], 2))

    return worklet

def index_sort(worklet,model,index):
    """
    Sorts the references in the 'Reference Work' section of the given worklet
    based on a sorted index generated by a language model.
    Args:
        worklet (dict): A dictionary containing the 'Reference Work' key, which
                        holds a list of references to be sorted.
        model (str): The identifier or configuration of the language model to
                        be used for generating the sorted indices.
        index (int): An index value used in fallback sorting logic.
    Returns:
        dict: The updated worklet with the 'Reference Work' section sorted
                based on the generated indices. If the sorting process fails,
                a fallback sorting method (`scholar_sort`) is used.
    Notes:
        - The function uses a language model to generate a sorted index based
            on the serialized 'Reference Work' data.
        - If the language model fails to generate valid indices, the function
            falls back to the `scholar_sort` method.
        - Duplicate indices are removed before rearranging the references.
    """

    reference_work_str = json.dumps(worklet['Reference Work'], indent=2)
    prompt =index_sort_template(reference_work_str)  
    sorted_indices = invoke_llm(prompt, model)
    sorted_indices=convert_to_list(sorted_indices)
    
    if sorted_indices == "failed":
        return scholar_sort(worklet,model,index)

    sorted_indices=remove_duplicates(sorted_indices)
    sorted_references = rearrange_references(worklet['Reference Work'], sorted_indices)
    worklet["Reference Work"] = sorted_references
    return worklet

def rearrange_references(reference_work, sorted_indices):
    rearranged_references = []
    for i in sorted_indices:
        if 0 <= i < len(reference_work):
            rearranged_references.append(reference_work[i])
            
    return rearranged_references

def convert_to_list(input_data):
    """
    Convert input_data to a list of integers safely.

    Handles:
    - Lists of integers directly.
    - Strings that are valid JSON lists (e.g., "[1, 2, 3]").
    - Strings containing a list inside text (e.g., "abc [1,2,3] xyz").
    - Strings of numbers separated by commas or spaces (e.g., "1,2,3" or "1 2 3").

    If parsing fails, returns True and prints a warning.
    """

    try:
        if isinstance(input_data, list):
            return [int(x) for x in input_data]

        elif isinstance(input_data, str):
            input_data = input_data.strip()

            # Try JSON loading first
            try:
                parsed = json.loads(input_data)
                if isinstance(parsed, list):
                    return [int(x) for x in parsed]
            except json.JSONDecodeError:
                pass

            # Try to find a list inside the string (e.g., "some text [1,2,3]")
            if '[' in input_data and ']' in input_data:
                start = input_data.find('[')
                end = input_data.find(']', start) + 1
                list_str = input_data[start:end]
                try:
                    parsed = ast.literal_eval(list_str)
                    if isinstance(parsed, list):
                        return [int(x) for x in parsed]
                except (ValueError, SyntaxError):
                    pass

            # Fallback: split by common separators
            separators = [",", " "]
            for sep in separators:
                if sep in input_data:
                    parts = input_data.split(sep)
                    return [int(x.strip()) for x in parts if x.strip().isdigit()]

        # If nothing worked
        raise ValueError

    except (ValueError, TypeError):
        
        return "failed"

def remove_duplicates(numbers):
    """Removes duplicates from a list while keeping order."""
    seen = set()
    unique_numbers = []
    for num in numbers:
        if num not in seen:
            seen.add(num)
            unique_numbers.append(num)
    return unique_numbers