import json

def extract_json_from_llm_response(llm_response):
    """
    Extracts and parses a JSON object from a response generated by an LLM (Large Language Model).
    This function removes any formatting artifacts such as backticks and the "json" keyword
    that might be present in the response, and then attempts to parse the cleaned string
    into a JSON object.
    Args:
        llm_response (str): The raw response string from the LLM, which is expected to contain
                            a JSON object, possibly wrapped in formatting artifacts.
    Returns:
        dict: The parsed JSON object.
    Raises:
        ValueError: If the cleaned string cannot be parsed as valid JSON.
    """
    
    raw_json_string = llm_response

    # Remove backticks and "json" keyword if present
    cleaned_json_string = raw_json_string.replace("```json", "").replace("```", "").strip()
    
    try:
        parsed_json = json.loads(cleaned_json_string)
        return parsed_json
    except json.JSONDecodeError as e:
        raise ValueError(f"Failed to parse JSON: {e}")

