name: Deploy to Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code (needed to trigger GitHub context properly)
        uses: actions/checkout@v3

      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.HOST }} >> ~/.ssh/known_hosts

      - name: SSH into Droplet and deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.HOST }} << 'EOF'
            set -e

            # Clone repo if needed
            if [ ! -d "/home/bedrock/backend" ]; then
              mkdir -p /home/bedrock
              cd /home/bedrock
              git clone git@github.com:bedrocksp/backend.git backend
            else
              cd /home/bedrock/backend
              git pull origin main
            fi

            cd /home/bedrock/backend

            # Create virtualenv if not exists
            if [ ! -d "parthenv" ]; then
              python3 -m venv parthenv
            fi

            # Activate venv and install/update dependencies
            source parthenv/bin/activate
            pip install --upgrade pip
            pip install -r droplet-req.txt

            # Restart systemd service
            sudo systemctl restart fastapi
          EOF
